# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shank_thigh_send.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16shank_thigh_send.proto\"\xe3\x01\n\x07LegData\x12)\n\x0bright_shank\x18\x01 \x02(\x0b\x32\x14.LegData.coordinates\x12(\n\nleft_shank\x18\x02 \x02(\x0b\x32\x14.LegData.coordinates\x12)\n\x0bright_thigh\x18\x03 \x02(\x0b\x32\x14.LegData.coordinates\x12(\n\nleft_thigh\x18\x04 \x02(\x0b\x32\x14.LegData.coordinates\x1a.\n\x0b\x63oordinates\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shank_thigh_send_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LEGDATA']._serialized_start=27
  _globals['_LEGDATA']._serialized_end=254
  _globals['_LEGDATA_COORDINATES']._serialized_start=208
  _globals['_LEGDATA_COORDINATES']._serialized_end=254
# @@protoc_insertion_point(module_scope)
